config/routes.rb
Rails.application.routes.draw do
  
  resources :documents
  root "documents#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :img
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/document_controller.rb
class DocumentsController < ApplicationController
  def new
    @document = Document.new
  end
  
  def index
    @document = Document.all
  end

  def show
    @document = Document.find(params[:id])
  end

  def edit
    @document = Document.find(params[:id])
  end
  
  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to document_path(@post)
    else
      @documents = Document.all
      render :new
    end
  end
  
  def delete
    
  end
  
  def update
    
  end

  private
  
  def document_params
    params.require(:document).permit(:title, :body)
  end
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def new
    @document = Document.new
  end
  
  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
  end

  def edit
    @document = Document.find(params[:id])
  end
  
  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to documents_path(@document)
    else
      @documents = Document.all
      render :new
    end
  end
  
  def delete
    
  end
  
  def update
    
  end

  private
  
  def document_params
    params.require(:document).permit(:title, :body)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/documents/edit.html.erb
<h1>Document#edit</h1>
<p>Find me in app/views/document/edit.html.erb</p>

app/views/documents/index.html.erb
<div class="container p-3">
  
    <% @documents.each do |document| %>
    <div class="card" style="width: 18rem;">
      <% if document.img.attached? %>
        <%= image_tag document.img, class: "card-img-top" %>
      <% else %>
        
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= document.title %></h5>
        <p class="card-text"><%= document.body %></p>
      </div>
    </div>
    <% end %>
    
  
</div>

app/views/documents/new.html.erb
<div class="container p-3">
  <div class="center-block">
    <h3>投稿文作成</h3>
    
    <%= form_with model: @document do |f| %>
      <p>表紙</p>
      <%= f.file_field :img %>
      <p>タイトル</p>
      <%= f.text_field :title, size: 50 %>
      <p>本文</p>
      <%= f.text_area :body, rows: 15, cols: 60, placeholder: "ここに本文を入力してください"%>
      <div class="text-right">
        <%= f.submit "投稿", class: "btn btn-sm btn-secondary mt-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/show.html.erb
<h1>Document#show</h1>
<p>Find me in app/views/document/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/37b4bbcd03.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
    crossorigin="anonymous">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-info">
        <div class="container">
          <div class="navbar-brand text-light">
            <i class="fa-solid fa-blog"></i>
            <span>WEBlog</span>
          </div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "ブログ一覧", documents_path, class: "btn btn-sm btn-outline-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規投稿", new_document_path, class: "btn btn-sm btn-outline-light" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>